export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_ROOT_COMMENTS = "FETCH_ROOT_COMMENTS";
export const FETCH_CHILD_COMMENTS = "FETCH_CHILD_COMMENTS";
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';